### PR TITLE
Update node version in action.yml

### PR DESCRIPTION
**Pull request by aknarts**

### CODE REVIEW

**Comment by aknarts** [comment]
Should have known this is not going to be as easy:)
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (evalmachine.<anonymous>:1:14[78](https://github.com/aknarts/trunk-action/actions/runs/8537190852/job/23387252712#step:3:79)571)
    at module.exports (evalmachine.<anonymous>:1:1480625)
    at runCmd (evalmachine.<anonymous>:1:46940)
    at 819 (evalmachine.<anonymous>:1:43967)
    at __webpack_require__ (evalmachine.<anonymous>:1:216)
    at startup (evalmachine.<anonymous>:1:353)
    at module.exports.8 (evalmachine.<anonymous>:1:385)
    at evalmachine.<anonymous>:1:395 {
  opensslErrorStack: [ 'error:030000[86](https://github.com/aknarts/trunk-action/actions/runs/8537190852/job/23387252712#step:3:87):digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by aknarts** [comment]
I am out of my depth with nodejs.

If I add the recommended `NODE_OPTIONS=--openssl-legacy-provider` to fix above issue I run into other issues during the ncc build
```
ncc: Version 0.20.5
ncc: Compiling file index.js
Skipping asset emission of /etc/lsb-release for /mnt/disk2/stastny/repos/trunk-action/node_modules/@actions/tool-cache/lib/manifest.js as it is outside the package base /mnt/disk2/stastny/repos/trunk-action/node_modules/@actions/tool-cache
Skipping asset emission of /etc/lsb-release for /mnt/disk2/stastny/repos/trunk-action/node_modules/@actions/tool-cache/lib/manifest.js as it is outside the package base /mnt/disk2/stastny/repos/trunk-action/node_modules/@actions/tool-cache
Error: Module parse failed: Unexpected character '#' (13:2)
```

Anyone can pick this up...

**Comment by jetli** [comment]
@aknarts fixed in this pr: https://github.com/jetli/trunk-action/pull/32, please upgrade this action to 0.5.0

**Comment by aknarts** [comment]
@jetli you are the best! And yeah I would not have managed that. Thanks for the update!

**Pull request closed without merging**
